name: Scheduled Homepage Build

on:
    schedule:
    # -   cron: 0 5,12,18 * * *
    -   cron: 5 * * * *

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   name: build request
            run: curl -X POST -d {} ${{ secrets.BUILD_HOOK }}